stages:
  - build

build:
  image: microsoft/dotnet:2.0-sdk
  before_script:
    - dotnet restore
  script:
    - dotnet publish -o "$(pwd)/build" -c Release LibAtem
    - cd LibAtem.Test
    - dotnet test
  stage: build
  tags:
    - docker
  artifacts:
    paths:
    - build/*
